/smoother_server:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    action_server_result_timeout: 10.0
    autostart_node: false
    bond_heartbeat_period: 0.1
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /tf:
        subscription:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        subscription:
          depth: 100
          history: keep_last
          reliability: reliable
    robot_base_frame: base_link
    savgol:
      do_refinement: true
      plugin: nav2_smoother::SavitzkyGolaySmoother
      refinement_num: 2
    simples:
      do_refinement: true
      max_its: 1000
      plugin: nav2_smoother::SimpleSmoother
      refinement_num: 2
      tolerance: 1.0e-10
      w_data: 0.2
      w_smooth: 0.3
    smoother_plugins:
    - suave
    - simples
    - savgol
    start_type_description_service: true
    suave:
      cost_check_points:
      - -0.185
      - 1.0
      - 0.0
      cusp_zone_length: 2.5
      keep_goal_orientation: false
      keep_start_orientation: true
      minimum_turning_radius: 0.37
      optimizer:
        debug_optimizer: false
        fn_tol: 1.0e-07
        gradient_tol: 1.0e-10
        linear_solver_type: SPARSE_NORMAL_CHOLESKY
        max_iterations: 100
        param_tol: 1.0e-15
      path_downsampling_factor: 3
      path_upsampling_factor: 1
      plugin: nav2_constrained_smoother/ConstrainedSmoother
      reversing_enabled: false
      w_cost: 0.015
      w_cost_cusp_multiplier: 3.0
      w_curve: 30.0
      w_dist: 0.0
      w_smooth: 15000.0
    transform_tolerance: 0.1
    use_sim_time: true

